FROM        ghcr.io/thaibault/containerbase:latest-x86-64

LABEL       maintainer="Torben Sickert <info@torben.website>"
LABEL       Description="test" Vendor="thaibault products" Version="1.0"

ENV         COMMAND '\'echo Application started. Main user name is \\\"\$USER\\\".\''
