name: Test encrypted build

on:
  # Runs when a new image was build.
  workflow_run:
    workflows:
      - 'Build image and push'
    branches:
      - main
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  encrypt:
    runs-on: ubuntu-latest
    container: ghcr.io/thaibault/containerbase:latest

    # NOTE: Theses environment variables are only needed to test the encrypt
    # script.
    env:
      DECRYPTED_PATHS: testSimple/
      ENCRYPTED_PATHS: testEncryption/
      PASSWORD_FILE_PATHS: testAdvanced/.encryptionPassword

    steps:
      - uses: actions/checkout@v3.1.0

      - run: ./scripts/encrypt.sh
      - run: ls --all --human-readable -l testEncryption

      - run: rm --force --recursive testEncryption
  buildAndRunSimple:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Build image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./testSimple
          push: false
          tags: test-simple:latest

      - uses: addnab/docker-run-action@v3
        with:
          image: test-simple:latest
          run: /usr/bin/initialize
  buildAndRunEnvironment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Build image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./testSimple
          push: false
          tags: test-environment:latest

      - uses: addnab/docker-run-action@v3
        with:
          image: test-environment:latest
          options: --mount type=bind,source=${{ github.workspace }}/testAdvanced/.encryptionPassword,target=/var/run/credentials/password
          run: /usr/bin/initialize
  buildAndRunAdvanced:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Build image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./testAdvanced
          push: false
          tags: test-advanced:latest

      # Decrypt with hidden mounted password file.
      - uses: addnab/docker-run-action@v3
        with:
          image: test-advanced:latest
          options: --mount type=bind,source=${{ github.workspace }}/testAdvanced/.encryptionPassword,target=/application/.encryptionPassword
          run: /usr/bin/initialize

      # Decrypt with password provided as command line argument
      - uses: addnab/docker-run-action@v3
        with:
          image: test-advanced:latest
          run: /usr/bin/initialize test

      # Decrypt with password provided as environment variable.
      - uses: addnab/docker-run-action@v3
        with:
          image: test-advanced:latest
          options: --env DECRYPTION_PASSWORD=test
          run: /usr/bin/initialize

      # Decrypt with password provided as secret.
      - uses: addnab/docker-run-action@v3
        with:
          image: test-advanced:latest
          options: --mount type=bind,source=${{ github.workspace }}/testAdvanced/.encryptionPassword,target=/run/secrets/encryption_password
          run: /usr/bin/initialize
